import type { Goal, Overview } from "@/lib/api";
import { CardHead, EarningsChart, money, type SourcedTransaction, TransactionTable } from "@/components/dashboard/shared";

type Total = Overview["totals"][number];

function Stat({ label, value, change, good, sub, icon }: { label: string; value: string; change?: string; good?: boolean; sub?: string; icon: string }) {
  return <article className="stat card"><div className="stat-icon">{icon}</div><p>{label}</p><h3>{value}</h3>{change ? <small className={good ? "good" : "muted"}>↗ {change} <span>from last month</span></small> : <small className="muted">{sub}</small>}</article>;
}

export function OverviewView({ displayName, overview, total, goal, transactions, onCurrency }: { displayName: string; overview: Overview; total: Total; goal?: Goal; transactions: SourcedTransaction[]; onCurrency: (currency: string) => void }) {
  return <><section className="welcome"><div><p className="eyebrow">YOUR EARNINGS TODAY</p><h2>Good to see you, {displayName.split(" ")[0]} <span>✦</span></h2><p>Here&apos;s how your earnings are looking.</p></div>{overview.totals.length > 0 && <div className="period currency-picker" aria-label="Displayed currency">{overview.totals.map((item) => <button key={item.currency} className={item.currency === total.currency ? "selected" : ""} onClick={() => onCurrency(item.currency)}>{item.currency}</button>)}</div>}</section><section className="stats"><Stat label="Net earnings" value={money(total.net, total.currency)} change="12.4%" good icon="↗"/><Stat label="Gross income" value={money(total.gross, total.currency)} change="8.2%" good icon="＋"/><Stat label="Fees paid" value={money(total.fees, total.currency)} change="2.1%" icon="−"/><Stat label="Active sources" value={String(overview.incomeSources.filter((source) => source.isActive).length)} sub="Across your accounts" icon="⌁"/></section><section className="dashboard-grid"><div className="card chart-card"><CardHead title="Earnings flow" action="Last 6 months⌄"/><div className="chart-summary"><div><small>Total earned</small><strong>{money(total.gross, total.currency)}</strong></div><div className="legend"><span><i className="net-dot"/>Net earnings</span><span><i/>Fees</span></div></div><EarningsChart/></div><div className="card goal-card"><CardHead title="Monthly goal" action="View goals →"/><div className="goal-ring" style={{"--progress": `${goal?.progressPercentage ?? 0}%`} as React.CSSProperties}><div><strong>{Math.round(goal?.progressPercentage ?? 0)}%</strong><small>complete</small></div></div><h3>{goal?.name ?? "Set your first goal"}</h3><p><strong>{money(goal?.currentAmount ?? 0, goal?.currency)}</strong> of {money(goal?.targetAmount ?? 0, goal?.currency)}</p><div className="goal-note">✦ You&apos;re {money(Math.max(0, (goal?.targetAmount ?? 0) - (goal?.currentAmount ?? 0)), goal?.currency)} away</div></div></section><section className="card recent"><CardHead title="Recent transactions" action="View all →"/><TransactionTable transactions={transactions.slice(0,5)}/></section></>;
}

function GoalsView({ goals, onCreate }: { goals: Goal[]; onCreate: () => void }) {
  const groups = [["Active goals", goals.filter((goal) => goal.status === "Active")], ["Achieved goals", goals.filter((goal) => goal.status === "Achieved")], ["Expired goals", goals.filter((goal) => goal.status === "Expired")]] as const;
  return <div className="goals-page"><div className="goals-toolbar"><div><p className="eyebrow">FINANCIAL TARGETS</p><h2>Turn every payment into progress.</h2></div><button className="primary" onClick={onCreate}>+ New goal</button></div>{groups.map(([title,items]) => items.length > 0 || title !== "Expired goals" ? <section className="goal-group" key={title}><div className="goal-group-head"><h2>{title}</h2><span>{items.length}</span></div>{items.length ? <div className="source-grid">{items.map((item) => <article className={`card source-card goal-item ${item.status.toLowerCase()}`} key={item.id}><span className="source-logo">{item.isAchieved ? "✓" : "◎"}</span><div><small>{item.status} · {item.startDate} to {item.targetDate}</small><h3>{item.name}</h3><div className="goal-progress"><i style={{width:`${item.progressPercentage}%`}}/></div><p>{Math.round(item.progressPercentage)}% complete</p></div><strong>{money(item.currentAmount,item.currency)} / {money(item.targetAmount,item.currency)}</strong></article>)}</div> : <div className="card goal-empty">No {title.toLowerCase()}.</div>}</section> : null)}</div>;
}

export function DashboardSection({ active, overview, transactions, onVerify, onCreateGoal }: { active: string; overview: Overview; transactions: SourcedTransaction[]; onVerify: () => void; onCreateGoal: () => void }) {
  if (active === "Transactions") return <section className="card page-card"><CardHead title="All transactions" action="Export CSV"/><TransactionTable transactions={transactions}/></section>;
  if (active === "Earnings") return <section className="source-grid">{overview.incomeSources.map((source) => <article className="card source-card" key={source.id}><span className="source-logo">{source.name[0]}</span><div><small>{source.provider}</small><h3>{source.name}</h3><p>{source.transactions.length} payments</p></div><strong>{money(source.transactions.reduce((sum,item) => sum + item.amount - item.fee,0),source.currency)}</strong></article>)}</section>;
  if (active === "Goals") return <GoalsView goals={overview.financialGoals} onCreate={onCreateGoal}/>;
  return <section className="connections"><div className="connection-intro demo-intro"><p className="eyebrow">QUICK PRODUCT DEMO</p><h2>See your dashboard update instantly.</h2><p>Add a clearly labelled fictional payment. No provider account or real money is needed.</p><button className="primary demo-cta" onClick={onVerify}>Try a demo payment</button></div><article className="card connection demo-connection"><span className="provider demo-provider">✦</span><div><h3>Demo payment</h3><p>Fast, fictional, and safe for anyone to try</p></div><span className="connected">Recommended</span></article>{["PayPal","Paystack"].map((name) => <article className="card connection" key={name}><span className={`provider ${name.toLowerCase()}`}>{name === "PayPal" ? "P" : "P₦"}</span><div><h3>{name}</h3><p>{name === "PayPal" ? "Sandbox test with buyer approval" : "Hosted test checkout and verification"}</p></div><span className="connection-tag">Advanced</span></article>)}</section>;
}
